spring.application.name=my_batis

spring.datasource.url=jdbc:postgresql://localhost:5432/my_batis_db
spring.datasource.username=postgres
spring.datasource.password=Nary123
spring.datasource.driver-class-name=org.postgresql.Driver


